chore: fixing docs->wiki sync and testing

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -105,21 +105,27 @@ jobs:
               git pull "$GIT_REPOSITORY_URL"
           )
 
-          debug "Syncing contents of Wiki to repository dir docs"
-          rsync -avzr --delete --exclude='.git/' "$tmp_dir/" "docs"
+          files_modified=$(diff -qr --exclude=.git docs/ $tmp_dir)
+          if [ files_modifies != "" ]; then
 
-          debug "Committing and pushing changes"
-          (
-              git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
-              git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
-              
-              # master could have been modified, so pull before pushing
-              git pull --ff-only origin master
-              
-              git add .
-              git commit -m "$WIKI_COMMIT_MESSAGE"
-              git push origin master
-          )
+            debug "Syncing contents of Wiki to repository dir docs"
+            rsync -avzr --delete --exclude='.git/' "$tmp_dir/" "docs"
+
+            debug "Committing and pushing changes"
+            (
+                git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
+                git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
+                
+                # master could have been modified, so pull before pushing
+                git pull --ff-only origin master
+                
+                git add .
+                git commit -m "$WIKI_COMMIT_MESSAGE"
+                git push origin master
+            )
+          else 
+            echo "No file diff between wiki and docs. Exiting."
+          fi 
           rm -rf "$tmp_dir"
           debug "Finished - Wiki synced to docs dir"
           exit 0
@@ -127,12 +133,99 @@ jobs:
   job-sync-docs-to-wiki:
     runs-on: ubuntu-latest
     if: github.event_name != 'gollum'
+    env:
+      GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.NEWRELIC_BOT_TOKEN }}
     steps:
-      - uses: actions/checkout@v2
-      # Additional steps to generate documentation in "Documentation" directory
-      - name: Upload Documentation to Wiki
-        uses: SwiftDocOrg/github-wiki-publish-action@v1
-        with:
-          path: "docs"
-        env:
-          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.NEWRELIC_BOT_TOKEN }}
+      # - uses: actions/checkout@v2
+      # # Additional steps to generate documentation in "Documentation" directory
+      # - name: Upload Documentation to Wiki
+      #   uses: SwiftDocOrg/github-wiki-publish-action@v1
+      #   with:
+      #     path: "docs"
+      #   env:
+      #     GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.NEWRELIC_BOT_TOKEN }}
+      - name: Checkout Repo
+        uses: actions/checkout@v2
+        # with:
+        #   token: ${{ secrets.NEWRELIC_BOT_TOKEN }} # allows us to push back to repo
+      - name: Sync docs to wiki
+        run: |
+          function debug() {
+              echo "::debug::$1"
+          }
+
+          function error() {
+              echo "::error::$1"
+          }
+
+          function add_mask() {
+              echo "::add-mask::$1"
+          }
+
+          # check that vars are set
+          if [ -z "$GITHUB_ACTOR" ]; then
+              error "GITHUB_ACTOR environment variable is not set"
+              exit 1
+          fi
+
+          if [ -z "$GITHUB_REPOSITORY" ]; then
+              error "GITHUB_REPOSITORY environment variable is not set"
+              exit 1
+          fi
+
+          if [ -z "$GH_PERSONAL_ACCESS_TOKEN" ]; then
+              error "GH_PERSONAL_ACCESS_TOKEN environment variable is not set"
+              exit 1
+          fi
+
+          add_mask "${GH_PERSONAL_ACCESS_TOKEN}"
+
+          if [ -z "${WIKI_COMMIT_MESSAGE:-}" ]; then
+              debug "WIKI_COMMIT_MESSAGE not set, using default"
+              WIKI_COMMIT_MESSAGE='chore(docs): Sync docs to wiki [skip ci]'
+          fi
+
+          GIT_REPOSITORY_URL="https://${GH_PERSONAL_ACCESS_TOKEN}@github.com/$GITHUB_REPOSITORY.wiki.git"
+
+          debug "Checking out wiki repository"
+          tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
+          (
+              cd "$tmp_dir" || exit 1
+              git init
+              git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
+              git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
+              git pull "$GIT_REPOSITORY_URL"
+          )
+
+          files_modified=$(diff -qr --exclude=.git docs/ $tmp_dir)
+          if [ files_modifies != "" ]; then
+
+            debug "Syncing contents of docs to wiki repository"
+            rsync -avzr --delete --exclude='.git/' "docs/" "$tmp_dir"
+
+            # debug "Committing and pushing changes"
+            # (
+            #     git config user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"
+            #     git config user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
+                
+            #     # master could have been modified, so pull before pushing
+            #     git pull --ff-only origin master
+                
+            #     git add .
+            #     git commit -m "$WIKI_COMMIT_MESSAGE"
+            #     git push origin master
+            # )
+
+            debug "Committing and pushing changes"
+            (
+                cd "$tmp_dir" || exit 1
+                git add .
+                git commit -m "$WIKI_COMMIT_MESSAGE"
+                git push --set-upstream "$GIT_REPOSITORY_URL" master
+            )
+          else 
+            echo "No file diff between docs and wiki. Exiting."
+          fi 
+          rm -rf "$tmp_dir"
+          debug "Finished - Wiki synced to docs dir"
+          exit 0
