fix: copying rest of action

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -53,19 +53,36 @@ jobs:
         run: |
 
           function debug() {
-              echo "::debug file=${BASH_SOURCE[0]},line=${BASH_LINENO[0]}::$1"
+              echo "::debug::$1"
           }
           function warning() {
-              echo "::warning file=${BASH_SOURCE[0]},line=${BASH_LINENO[0]}::$1"
+              echo "::warning::$1"
           }
 
           function error() {
-              echo "::error file=${BASH_SOURCE[0]},line=${BASH_LINENO[0]}::$1"
+              echo "::error::$1"
           }
-
+          
           function add_mask() {
               echo "::add-mask::$1"
           }
+
+          if [ -z "$GITHUB_ACTOR" ]; then
+              error "GITHUB_ACTOR environment variable is not set"
+              exit 1
+          fi
+
+          if [ -z "$GITHUB_REPOSITORY" ]; then
+              error "GITHUB_REPOSITORY environment variable is not set"
+              exit 1
+          fi
+
+          if [ -z "$GH_PERSONAL_ACCESS_TOKEN" ]; then
+              error "GH_PERSONAL_ACCESS_TOKEN environment variable is not set"
+              exit 1
+          fi
+
+          add_mask "${GH_PERSONAL_ACCESS_TOKEN}"
 
           GIT_REPOSITORY_URL="https://${GH_PERSONAL_ACCESS_TOKEN}@github.com/$GITHUB_REPOSITORY.wiki.git"
 
